/**
 * This is a temporary hard-coded snapshot of prospect data.
 */
export const PROSPECT_INFO = [
  { title: "LinkedIn", value: "No LinkedIn" },
  { title: "Mobile Phone (Default)", value: "No Phone" },
  { title: "consent_date", value: "YYYY-MM-DD" },
  { title: "consent_for_call", value: "No consent_for_call" },
  { title: "Account", value: "No Account" },
  { title: "hippo_product", value: "No hippo_product" },
  { title: "City", value: "No City" },
  { title: "Work Email (Default)", value: "eg-outplay123@maritnz.co.in" },
  { title: "First Name", value: "outplay123" },
  { title: "Last Name", value: "No Last Name" },
  { title: "Title", value: "No Title" },
  { title: "company", value: "No company" },
  { title: "Tags", value: "No tags" },
  { title: "Stage", value: "No Stage" },
  { title: "Time Zone", value: "No Time Zone" },
  { title: "Prospect Interests", value: "No Prospect Interests" },
  { title: "010", value: "No 010" },
  { title: "1234", value: "No 1234" },
  { title: "abc_number", value: "No abc_number" },
  { title: "account_custom12", value: "No account_custom12" },
  { title: "akash_lookup", value: "No akash_lookup" },
  { title: "akash_num", value: "No akash_num" },
  { title: "asa", value: "No asa" },
  { title: "asdf", value: "No asdf" },
  { title: "asdfg", value: "No asdfg" },
  { title: "bjkhj", value: "No bjkhj" },
  { title: "call", value: "No call" },
  { title: "checking", value: "No checking" },
  { title: "checking_check", value: "No checking_check" },
  { title: "checkingppnew", value: "No checkingppnew" },
  { title: "cnct_lkp", value: "No cnct_lkp" },
  { title: "co_owner", value: "No co_owner" },
  { title: "contact_type", value: "No contact_type" },
  { title: "coowned", value: "No coowned" },
  { title: "coownerw", value: "No coownerw" },
  { title: "Country", value: "No Country" },
  { title: "cust_date_dev", value: "YYYY-MM-DD" },
  { title: "cust_multiline", value: "   " },
  { title: "cust_num_dev", value: "No cust_num_dev" },
  { title: "cust_picklist_dev", value: "No cust_picklist_dev" },
  { title: "cust_plkpfld_dev", value: "No cust_plkpfld_dev" },
  { title: "cust_text_dev", value: "No cust_text_dev" },
  { title: "cust_ulkpfld_dev", value: "No cust_ulkpfld_dev" },
  { title: "cust_url_dev", value: "No cust_url_dev" },
  { title: "custom_number", value: "No custom_number" },
  { title: "dadasaa", value: "No dadasaa" },
  { title: "date1", value: "YYYY-MM-DD" },
  { title: "datetime_krishna", value: "yyyy-mm-dd hh:mm" },
  { title: "ddadas", value: "No ddadas" },
  { title: "dddd", value: "No dddd" },
  { title: "dee", value: "No dee" },
  { title: "dfdfd", value: "YYYY-MM-DD" },
  { title: "dfdsf", value: "No dfdsf" },
  { title: "dsd", value: "No dsd" },
  { title: "dsdsds", value: "No dsdsds" },
  { title: "dual_owner", value: "No dual_owner" },
  { title: "dualowner_d_450777", value: "No dualowner_d_450777" },
  { title: "enter", value: "YYYY-MM-DD" },
  { title: "Facebook", value: "No Facebook" },
  { title: "farooq", value: "No farooq" },
  { title: "farooq_date", value: "YYYY-MM-DD" },
  { title: "farooq_date_time", value: "yyyy-mm-dd hh:mm" },
  { title: "farooq_lookup", value: "No farooq_lookup" },
  { title: "farooq_multiline", value: "   " },
  { title: "farooq_number", value: "No farooq_number" },
  { title: "farooq_picklist", value: "No farooq_picklist" },
  { title: "farooq_single_select", value: "No farooq_single_select" },
  { title: "farooq_text", value: "No farooq_text" },
  { title: "farooq_url", value: "No farooq_url" },
  { title: "fdbfdbdb", value: "No fdbfdbdb" },
  { title: "fdf", value: "No fdf" },
  { title: "fhb", value: "No fhb" },
  { title: "field", value: "No field" },
  { title: "fieldprospect", value: "No fieldprospect" },
  { title: "ggg", value: "No ggg" },
  { title: "gkd", value: "No gkd" },
  { title: "hello_its_me", value: "No hello_its_me" },
  { title: "hello1", value: "No hello1" },
  { title: "hvjh", value: "No hvjh" },
  { title: "jatinlookup", value: "Harshit Rai" },
  { title: "jatinpicklist", value: "No jatinpicklist" },
  { title: "jatintest1", value: "No jatintest1" },
  { title: "jatintest10", value: "No jatintest10" },
  { title: "jatintest11", value: "No jatintest11" },
  { title: "jatintest12", value: "No jatintest12" },
  { title: "jatintest13", value: "No jatintest13" },
  { title: "jatintest14", value: "No jatintest14" },
  { title: "jatintest15", value: "No jatintest15" },
  { title: "jatintest16", value: "No jatintest16" },
  { title: "jatintest17", value: "No jatintest17" },
  { title: "jatintest18", value: "No jatintest18" },
  { title: "jatintest2", value: "No jatintest2" },
  { title: "jatintest3", value: "No jatintest3" },
  { title: "jatintest4", value: "No jatintest4" },
  { title: "jatintest5", value: "No jatintest5" },
  { title: "jatintest6", value: "No jatintest6" },
  { title: "jatintest7", value: "No jatintest7" },
  { title: "jatintest8", value: "No jatintest8" },
  { title: "jatintest9", value: "No jatintest9" },
  { title: "jhgjh", value: "No jhgjh" },
  { title: "kjghvbjndsfsdf", value: "No kjghvbjndsfsdf" },
  { title: "lambdatest", value: "No lambdatest" },
  { title: "languagesawf", value: "No languagesawf" },
  { title: "leon_custom", value: "No leon_custom" },
  { title: "longpicklistvalue2", value: "No longpicklistvalue2" },
  { title: "look_user", value: "No look_user" },
  { title: "look1", value: "No look1" },
  { title: "look2", value: "No look2" },
  { title: "look3", value: "No look3" },
  { title: "look5", value: "No look5" },
  { title: "lookup", value: "No lookup" },
  { title: "lookup_lead", value: "No lookup_lead" },
  { title: "lookup_leadac", value: "No lookup_leadac" },
  { title: "lookup_leadeal", value: "No lookup_leadeal" },
  { title: "lookupfield", value: "No lookupfield" },
  { title: "maheshbabu_up", value: "No maheshbabu_up" },
  { title: "mahii07", value: "No mahii07" },
  { title: "me14", value: "No me14" },
  { title: "meeting_date", value: "YYYY-MM-DD" },
  { title: "mjlis", value: "No mjlis" },
  { title: "multi_line", value: "   " },
  { title: "new", value: "No new" },
  { title: "new_f", value: "No new_f" },
  { title: "newce", value: "No newce" },
  { title: "newcelookup", value: "No newcelookup" },
  { title: "newpicklistfield", value: "No newpicklistfield" },
  { title: "olp", value: "No olp" },
  { title: "op_cust_user_al", value: "No op_cust_user_al" },
  { title: "op_test_cf_prospect_lkk", value: "No op_test_cf_prospect_lkk" },
  { title: "oppplookup", value: "No oppplookup" },
  { title: "out_datefield", value: "YYYY-MM-DD" },
  { title: "out_nopicklist", value: "No out_nopicklist" },
  { title: "out_numfield", value: "No out_numfield" },
  { title: "out_textfield", value: "No out_textfield" },
  { title: "out_textpicklist", value: "No out_textpicklist" },
  { title: "owner_2", value: "No owner_2" },
  { title: "owners", value: "No owners" },
  { title: "p_a1_1", value: "No p_a1_1" },
  { title: "pancard", value: "No pancard" },
  { title: "passport", value: "No passport" },
  { title: "pick_list", value: "No pick_list" },
  { title: "pick1", value: "No pick1" },
  { title: "pick2", value: "No pick2" },
  { title: "picklist2", value: "No picklist2" },
  { title: "picklistest", value: "No picklistest" },
  { title: "plp", value: "No plp" },
  { title: "pratiktestdualowner", value: "No pratiktestdualowner" },
  { title: "prosp_lookupfield", value: "No prosp_lookupfield" },
  { title: "prospect_user_lp", value: "No prospect_user_lp" },
  { title: "raghu", value: "No raghu" },
  { title: "raghu11", value: "No raghu11" },
  { title: "rahane", value: "No rahane" },
  { title: "rl_lup", value: "No rl_lup" },
  { title: "rln", value: "No rln" },
  { title: "rln2", value: "No rln2" },
  { title: "rln3", value: "YYYY-MM-DD" },
  { title: "rrrrr", value: "No rrrrr" },
  { title: "rufus_customf1", value: "No rufus_customf1" },
  { title: "sdsds", value: "No sdsds" },
  { title: "sdsf", value: "No sdsf" },
  { title: "sec12", value: "No sec12" },
  { title: "shubha", value: "No shubha" },
  { title: "spiderman", value: "No spiderman" },
  { title: "State", value: "No State" },
  { title: "states_visited", value: "No states_visited" },
  { title: "status", value: "No status" },
  { title: "surname", value: "No surname" },
  { title: "teset12", value: "No teset12" },
  { title: "test", value: "No test" },
  { title: "test_date1", value: "YYYY-MM-DD" },
  { title: "test_numb", value: "No test_numb" },
  { title: "test_s_text", value: "No test_s_text" },
  { title: "test1", value: "No test1" },
  { title: "tookan_product", value: "No tookan_product" },
  { title: "trext", value: "No trext" },
  { title: "Twitter", value: "No Twitter" },
  { title: "url_raghav", value: "No url_raghav" },
  { title: "userlookup_ad", value: "No userlookup_ad" },
  { title: "vinay_updated", value: "No vinay_updated" },
  { title: "yelo_product_purchase", value: "No yelo_product_purchase" },
  { title: "SDR First Touch Date", value: "Dec 11, 2025 4:44 PM" },
  { title: "Created Date", value: "Dec 11, 2025 4:44 PM" },
  { title: "Last Contacted Date", value: "Dec 12, 2025 11:50 AM" },
  { title: "Last Modified Date", value: "Dec 23, 2025 12:05 PM" }
];
